version: "3"
services:
  worksy-app:
    container_name: worksy-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes: 
      - ./src:/app/src:ro
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    volumes:
      - postgres-db:/var/lib/postgresql/data
    # set shared memory limit when using docker compose
    shm_size: 128m  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: worksy
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080    
volumes:
  postgres-db:

